# Generated by Django 5.2.6 on 2025-10-23 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=20)),
                (
                    "technologies",
                    models.TextField(
                        help_text="Comma-separated list of technologies used"
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("project_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField()),
                ("order", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Font Awesome icon class, e.g. 'fas fa-robot'",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField()),
            ],
            options={
                "verbose_name": "Project Category",
                "verbose_name_plural": "Project Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("download_url", models.URLField()),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project File",
                "verbose_name_plural": "Project Files",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
