# Generated by Django 5.2.6 on 2025-11-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
