# Generated by Django 5.2.6 on 2025-11-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="order",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
