# Generated by Django 5.2.6 on 2025-11-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_service_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(max_length=20),
        ),
    ]
