# Generated by Django 5.2.6 on 2025-11-02 16:08

from django.db import migrations, models
import django.db.models.deletion

def convert_category_char_to_foreign_key(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    
    # Mapping of old category values to new category objects
    category_mapping = {
        'medical': ServiceCategory.objects.get(name='Medical'),
        'food': ServiceCategory.objects.get(name='Food'),
        'marketing': ServiceCategory.objects.get(name='Marketing'),
        'ai': ServiceCategory.objects.get(name='AI'),
        'data': ServiceCategory.objects.get(name='Data'),
        'cloud': ServiceCategory.objects.get(name='Cloud'),
    }
    
    # Update all services with the new foreign key references
    for service in Service.objects.all():
        if service.category in category_mapping:
            service.category_fk = category_mapping[service.category]
            service.save()

def reverse_convert_category_foreign_key(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    
    # Mapping of category objects to old category values
    category_mapping = {
        'Medical': 'medical',
        'Food': 'food',
        'Marketing': 'marketing',
        'AI': 'ai',
        'Data': 'data',
        'Cloud': 'cloud',
    }
    
    # Update all services with the old char values
    for service in Service.objects.all():
        category_name = service.category_fk.name if service.category_fk else 'other'
        service.category = category_mapping.get(category_name, 'other')
        service.save()

class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_service_category"),
    ]

    operations = [
        # Add the new foreign key field
        migrations.AddField(
            model_name='service',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_old', to='services.servicecategory'),
        ),
        # Run the data migration
        migrations.RunPython(convert_category_char_to_foreign_key, reverse_convert_category_foreign_key),
        # Remove the old char field
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        # Rename the new foreign key field to the original name
        migrations.RenameField(
            model_name='service',
            old_name='category_fk',
            new_name='category',
        ),
        # Make the field non-nullable
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
    ]