# Generated by Django 5.2.6 on 2025-11-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_auto_20251102_2138"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(max_length=20),
        ),
    ]
