# Generated by Django 5.2.6 on 2025-11-02 16:16

from django.db import migrations, models
import django.db.models.deletion

def convert_category_char_to_foreign_key(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    
    # Create a mapping of category names to ServiceCategory objects
    category_mapping = {}
    for category in ServiceCategory.objects.all():
        category_mapping[category.name.lower()] = category
    
    # Get or create a default category for services without a valid category
    default_category, created = ServiceCategory.objects.get_or_create(
        name='Other',
        defaults={
            'description': 'Other services',
            'icon_class': 'fas fa-question-circle',
            'order': 999
        }
    )
    
    # Update all services with the new foreign key references
    for service in Service.objects.all():
        category_name = service.category.lower() if service.category else 'other'
        if category_name in category_mapping:
            service.category_fk = category_mapping[category_name]
        else:
            service.category_fk = default_category
        service.save()

def reverse_convert_category_foreign_key(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    
    # Update all services with the old char values
    for service in Service.objects.all():
        if service.category_fk:
            service.category = service.category_fk.name.lower()
        else:
            service.category = 'other'
        service.save()

class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_service_category"),
    ]

    operations = [
        # Add the new foreign key field
        migrations.AddField(
            model_name='service',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_old', to='services.servicecategory'),
        ),
        # Run the data migration
        migrations.RunPython(convert_category_char_to_foreign_key, reverse_convert_category_foreign_key),
        # Remove the old char field
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        # Rename the new foreign key field to the original name
        migrations.RenameField(
            model_name='service',
            old_name='category_fk',
            new_name='category',
        ),
    ]