# Generated by Django 5.2.6 on 2025-11-02 16:16

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_auto_20251102_2146"),
    ]

    operations = [
        # Make the field non-nullable
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
    ]