# Generated by Django 5.2.6 on 2025-11-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("Project Discussion", "Project Discussion"),
                            ("Service Inquiry", "Service Inquiry"),
                            ("Freelance Work", "Freelance Work"),
                            ("General Consultation", "General Consultation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date", "time"],
            },
        ),
    ]
