# Generated by Django 5.2.6 on 2025-11-21 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("client_company", models.CharField(blank=True, max_length=100)),
                ("client_location", models.CharField(max_length=100)),
                (
                    "client_type",
                    models.CharField(
                        choices=[("indian", "Indian"), ("foreign", "Foreign")],
                        default="indian",
                        max_length=10,
                    ),
                ),
                ("rating", models.IntegerField(help_text="Rating from 1-5")),
                ("testimonial_text", models.TextField()),
                ("project_name", models.CharField(blank=True, max_length=200)),
                ("date", models.DateField()),
                ("order", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="about.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order", "-date"],
            },
        ),
    ]
