# Generated by Django 5.2.6 on 2025-11-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelancing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="icon_class",
            field=models.CharField(default="fas fa-briefcase", max_length=50),
        ),
    ]
